apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: certbot
spec:
  type: ClusterIP
  ports:
  - name: certbot
    port: 80
    targetPort: 80
    protocol: TCP
  - name: certbot-ssl
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: certbot
