apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: certbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certbot
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: default
