apiVersion: batch/v1
kind: Job
metadata:
  name: certbot-renewal
  namespace: default
spec:
  template:
    metadata:
      name: certbot-renewal
    spec:
      serviceAccountName: certbot
      containers:
      - name: certbot-renewal
        imagePullPolicy: Always
        image: bouwe/certbot-kubernetes-secrets-aws:1.0.1
        command: ['python','-u','watch.py']
        envFrom:
          - configMapRef:
              name: certbot-configmap
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: data
          mountPath: /etc
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ssd
      resources:
        requests:
          storage: 1Gi